version: '3.8'
services:
  php-apache-environment:
    container_name : php-crud
    build : 
     context : .
    depends_on :
      - db
    volumes:
      - ./webform:/var/www/html/
    ports:
      - 8000:80
    env_file:
      - .env
  db:
    container_name : php-crud-mysql
    image : mysql
    restart : always
    environment : 
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - 9906:3306
    volumes:
      - mysql-php-volume:/var/lib/mysql
  phpmyadmin:
    image : phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart : always
    environment : 
      PMA_HOST: db
    depends_on:
      - db
volumes:
  mysql-php-volume:  